spring.application.name=SpringBoot1
# 파이썬 주석과 동일, 스프링 부트의 모든 환경설정을 하는 파일!

# context Path :
# tomcat server가 web application을 구분하기 위한 용도
# 기본값 : 프로젝트 이름
server.servlet.context-path=/web
server.port=8087

# controller 패키지 스캔을 할 수 있도록 환경설정
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# JDBC Driver -> 라이브러리 설치
# mybatis 라이브러리 필요
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/com
spring.datasource.username=com
spring.datasource.password=com01


